# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\views\uis\gacha_tower.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src\\views\\uis\\ps_ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MainBackground = QtWidgets.QWidget(MainWindow)
        self.MainBackground.setObjectName("MainBackground")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.MainBackground)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.MainBackground)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.maintab = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.maintab.setFont(font)
        self.maintab.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.maintab.setStyleSheet("QTabBar::tab {\n"
"    border: 4px solid rgb(255, 137, 1);\n"
"    padding: 15px;\n"
"    color: rgb(255, 137, 1);\n"
"    background-color: rgb(255, 0, 4);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color:rgb(255, 137, 1);\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    color: white;\n"
"    background-color: rgb(215, 97, 0);\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane {\n"
"    border: 2px solid rgb(255, 137, 1);\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"alignment: center;\n"
"}")
        self.maintab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.maintab.setObjectName("maintab")
        self.inicializador = QtWidgets.QWidget()
        self.inicializador.setObjectName("inicializador")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inicializador)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.red_frame = QtWidgets.QFrame(self.inicializador)
        self.red_frame.setStyleSheet("/*background-color: rgb(255, 0, 4);")
        self.red_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.red_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.red_frame.setObjectName("red_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.red_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.red_frame)
        self.label_15.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 20pt \"Arial Black\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.verticalLayout_2.addWidget(self.red_frame)
        self.blue_frame = QtWidgets.QFrame(self.inicializador)
        self.blue_frame.setStyleSheet("/*background-color: rgb(0, 0, 255);")
        self.blue_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blue_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.blue_frame.setObjectName("blue_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.blue_frame)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.amount_pego = QtWidgets.QLineEdit(self.blue_frame)
        self.amount_pego.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.amount_pego.setObjectName("amount_pego")
        self.gridLayout_3.addWidget(self.amount_pego, 1, 2, 1, 1)
        self.amount_gacha = QtWidgets.QLineEdit(self.blue_frame)
        self.amount_gacha.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.amount_gacha.setObjectName("amount_gacha")
        self.gridLayout_3.addWidget(self.amount_gacha, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.blue_frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("src\\views\\uis\\pego100.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.blue_frame)
        self.label_14.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 14pt \"Arial Black\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.blue_frame)
        self.label_10.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 14pt \"Arial Black\";color: rgb(255, 137, 1);\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 1, 1, 1)
        self.amount_trap = QtWidgets.QLineEdit(self.blue_frame)
        self.amount_trap.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.amount_trap.setFrame(True)
        self.amount_trap.setObjectName("amount_trap")
        self.gridLayout_3.addWidget(self.amount_trap, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.blue_frame)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("src\\views\\uis\\trap100.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.blue_frame)
        self.label_9.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 14pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.blue_frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("src\\views\\uis\\gacha100.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.blue_frame)
        self.yellow_frame = QtWidgets.QFrame(self.inicializador)
        self.yellow_frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.yellow_frame.setStyleSheet("/*background-color: rgb(255, 255, 0);")
        self.yellow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yellow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.yellow_frame.setObjectName("yellow_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.yellow_frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.yellow_frame)
        self.checkBox.setMaximumSize(QtCore.QSize(161, 16777215))
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    color: rgb(120, 120, 120);\n"
"    font-size: 16px;\n"
"    font-family: \"Arial\";\n"
"    spacing: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 6px;\n"
"    background-color: rgb(24, 24, 24);\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(255, 137, 1);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(255, 137, 1);\n"
"    border: 2px solid rgb(255, 137, 1);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: rgb(255, 160, 40);\n"
"    border: 2px solid rgb(255, 160, 40);\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout_2.addWidget(self.yellow_frame)
        self.green_frame = QtWidgets.QFrame(self.inicializador)
        self.green_frame.setStyleSheet("/*background-color: rgb(0, 255, 29);")
        self.green_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.green_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.green_frame.setObjectName("green_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.green_frame)
        self.gridLayout_4.setContentsMargins(9, 0, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.green_frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 72))
        self.pushButton.setMaximumSize(QtCore.QSize(370, 16777215))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 137, 1);\n"
"border: 3px outset rgb(93, 49, 0);\n"
"border-radius: 10px;\n"
"color: rgb(15, 15, 15);\n"
"    font: 87 20pt \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(215, 97, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 3px inset rgb(93, 49, 0);\n"
"color: rgb(15, 15, 15);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #cccccc; /* Cinza */\n"
"border: 2px solid #999999;\n"
"color: #666666; /* Texto cinza escuro */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.green_frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 72))
        self.pushButton_2.setMaximumSize(QtCore.QSize(370, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 137, 1);\n"
"border: 3px outset rgb(93, 49, 0);\n"
"border-radius: 10px;\n"
"color: rgb(15, 15, 15);\n"
"    font: 87 20pt \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(215, 97, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 3px inset rgb(93, 49, 0);\n"
"color: rgb(15, 15, 15);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #cccccc; /* Cinza */\n"
"border: 2px solid #999999;\n"
"color: #666666; /* Texto cinza escuro */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.green_frame)
        self.cyan_frame = QtWidgets.QFrame(self.inicializador)
        self.cyan_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.cyan_frame.setStyleSheet("/*background-color: rgb(0, 230, 255);")
        self.cyan_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cyan_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cyan_frame.setObjectName("cyan_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cyan_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fotologo = QtWidgets.QLabel(self.cyan_frame)
        self.fotologo.setMinimumSize(QtCore.QSize(50, 50))
        self.fotologo.setMaximumSize(QtCore.QSize(50, 50))
        self.fotologo.setText("")
        self.fotologo.setPixmap(QtGui.QPixmap("src\\views\\uis\\ps_png.png"))
        self.fotologo.setScaledContents(True)
        self.fotologo.setObjectName("fotologo")
        self.horizontalLayout.addWidget(self.fotologo)
        self.verticalLayout_2.addWidget(self.cyan_frame)
        self.maintab.addTab(self.inicializador, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.config)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.red_frame_2 = QtWidgets.QFrame(self.config)
        self.red_frame_2.setMaximumSize(QtCore.QSize(16777215, 87))
        self.red_frame_2.setStyleSheet("/*background-color: rgb(255, 0, 0);")
        self.red_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.red_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.red_frame_2.setObjectName("red_frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.red_frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.red_frame_2)
        self.label_3.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 20pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.verticalLayout_6.addWidget(self.red_frame_2)
        self.green_frame_2 = QtWidgets.QFrame(self.config)
        self.green_frame_2.setMaximumSize(QtCore.QSize(16777215, 31))
        self.green_frame_2.setStyleSheet("/*background-color: rgb(0, 255, 0);")
        self.green_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.green_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.green_frame_2.setObjectName("green_frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.green_frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.green_frame_2)
        self.label_5.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 15pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout_6.addWidget(self.green_frame_2)
        self.white_frame = QtWidgets.QFrame(self.config)
        self.white_frame.setMaximumSize(QtCore.QSize(16777215, 58))
        self.white_frame.setStyleSheet("/*background-color: rgb(255, 255, 255);")
        self.white_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.white_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.white_frame.setObjectName("white_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.white_frame)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.white_frame)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.white_frame)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.white_frame)
        self.label_6.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.white_frame)
        self.label_7.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.white_frame)
        self.purple_frame = QtWidgets.QFrame(self.config)
        self.purple_frame.setMaximumSize(QtCore.QSize(16777215, 32))
        self.purple_frame.setStyleSheet("/*background-color: rgb(183, 0, 255);")
        self.purple_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.purple_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.purple_frame.setObjectName("purple_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.purple_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.purple_frame)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 15pt \"Arial Black\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.verticalLayout_6.addWidget(self.purple_frame)
        self.cyan_frame_2 = QtWidgets.QFrame(self.config)
        self.cyan_frame_2.setStyleSheet("/*background-color: rgb(5, 230, 255);")
        self.cyan_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cyan_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cyan_frame_2.setObjectName("cyan_frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cyan_frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_22.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_2.addWidget(self.lineEdit_22, 4, 5, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_12.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 5, 2, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_18.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 1, 5, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_16.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_28.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 4, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_23.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_2.addWidget(self.lineEdit_23, 5, 5, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_30.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 3, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_20.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_18.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_32.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 5, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_31.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 4, 4, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 3, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_29.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 2, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 4, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_21.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_2.addWidget(self.lineEdit_21, 3, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_19.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_22.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_12.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_21.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 6, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_24.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_2.addWidget(self.lineEdit_24, 6, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_33.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 6, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.cyan_frame_2)
        self.label_13.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_20.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 2, 5, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.cyan_frame_2)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit_13.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 6, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.cyan_frame_2)
        self.Blue_Frame = QtWidgets.QFrame(self.config)
        self.Blue_Frame.setMaximumSize(QtCore.QSize(16777215, 32))
        self.Blue_Frame.setStyleSheet("/*background-color: rgb(0, 25, 255);")
        self.Blue_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Blue_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Blue_Frame.setObjectName("Blue_Frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Blue_Frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_24 = QtWidgets.QLabel(self.Blue_Frame)
        self.label_24.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 15pt \"Arial Black\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.verticalLayout_6.addWidget(self.Blue_Frame)
        self.yellow_frame_2 = QtWidgets.QFrame(self.config)
        self.yellow_frame_2.setStyleSheet("/*background-color: rgb(251, 255, 0);")
        self.yellow_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yellow_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.yellow_frame_2.setObjectName("yellow_frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.yellow_frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_27 = QtWidgets.QLabel(self.yellow_frame_2)
        self.label_27.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 3, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 2, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_14.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_5.addWidget(self.lineEdit_14, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.yellow_frame_2)
        self.label_17.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.yellow_frame_2)
        self.label_34.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 4, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_15.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_5.addWidget(self.lineEdit_15, 1, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_16.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_5.addWidget(self.lineEdit_16, 2, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(245, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 1, 4, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_17.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_5.addWidget(self.lineEdit_17, 4, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.yellow_frame_2)
        self.label_25.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.yellow_frame_2)
        self.label_26.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.yellow_frame_2)
        self.label_23.setStyleSheet("color: rgb(255, 137, 1);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 1, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_25.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_5.addWidget(self.lineEdit_25, 4, 3, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.yellow_frame_2)
        self.lineEdit_19.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 8px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 1px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1x solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_5.addWidget(self.lineEdit_19, 3, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.yellow_frame_2)
        self.dark_red_frame = QtWidgets.QFrame(self.config)
        self.dark_red_frame.setStyleSheet("/*background-color: rgb(136, 0, 0);")
        self.dark_red_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dark_red_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dark_red_frame.setObjectName("dark_red_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.dark_red_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.dark_red_frame)
        self.pushButton_3.setMaximumSize(QtCore.QSize(390, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 137, 1);\n"
"border: 3px outset rgb(93, 49, 0);\n"
"border-radius: 10px;\n"
"color: rgb(15, 15, 15);\n"
"    font: 87 20pt \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(215, 97, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 3px inset rgb(93, 49, 0);\n"
"color: rgb(15, 15, 15);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #cccccc; /* Cinza */\n"
"border: 2px solid #999999;\n"
"color: #666666; /* Texto cinza escuro */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.verticalLayout_6.addWidget(self.dark_red_frame)
        self.pink_frame = QtWidgets.QFrame(self.config)
        self.pink_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pink_frame.setStyleSheet("/*background-color: rgb(241, 76, 255);")
        self.pink_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pink_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pink_frame.setObjectName("pink_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.pink_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.pink_frame)
        self.label_4.setMinimumSize(QtCore.QSize(50, 50))
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("src\\views\\uis\\ps_png.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_6.addWidget(self.pink_frame)
        self.maintab.addTab(self.config, "")
        self.verticalLayout_8.addWidget(self.maintab)
        self.horizontalLayout_4.addWidget(self.frame)
        MainWindow.setCentralWidget(self.MainBackground)

        self.retranslateUi(MainWindow)
        self.maintab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.amount_gacha, self.amount_pego)
        MainWindow.setTabOrder(self.amount_pego, self.amount_trap)
        MainWindow.setTabOrder(self.amount_trap, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gacha Tower Bot"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Prime Survivor<br/>Gacha Tower Bot</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Quantidade de casais de gacha:"))
        self.label_10.setText(_translate("MainWindow", "Quantidade de casas de pegomastax"))
        self.label_9.setText(_translate("MainWindow", "Quantidade de trap farmers"))
        self.checkBox.setText(_translate("MainWindow", "Test Gacha Mode"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar"))
        self.pushButton_2.setText(_translate("MainWindow", "Parar (F10)"))
        self.maintab.setTabText(self.maintab.indexOf(self.inicializador), _translate("MainWindow", "Gacha Tower Bot"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ConfiguraçãoGacha Tower Bot</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Calibragem</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Direção da Gacha Tower: "))
        self.label_7.setText(_translate("MainWindow", "Pixel por Grau: "))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Coordenadas</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">(X, Y)</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "Inventario Dino (Search):"))
        self.label_30.setText(_translate("MainWindow", "Inventario Dino (Drop All):"))
        self.label_20.setText(_translate("MainWindow", "Inventario Player (Transfer All):"))
        self.label_18.setText(_translate("MainWindow", "Teleport (Botão Teleportar):"))
        self.label_32.setText(_translate("MainWindow", "Menu Cama Tek (Lay):"))
        self.label_31.setText(_translate("MainWindow", "Inventario Dino (Primeiro Slot):"))
        self.label_29.setText(_translate("MainWindow", "Inventario Dino (Transfer All):"))
        self.label_19.setText(_translate("MainWindow", "Inventario Player (Search):"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">(X, Y)</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Teleport (Search Map):"))
        self.label_21.setText(_translate("MainWindow", "Inventario Player (Drop All):"))
        self.label_33.setText(_translate("MainWindow", "Inventario Grinder (Grind All):"))
        self.label_13.setText(_translate("MainWindow", "Teleport (Primeiro da lista):"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Validadores</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "Menu Cama Tek"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">(X, Y)</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "Vault Cheio"))
        self.label_25.setText(_translate("MainWindow", "Inventario"))
        self.label_26.setText(_translate("MainWindow", "Teleport"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Color(R, G, B)</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Salvar"))
        self.maintab.setTabText(self.maintab.indexOf(self.config), _translate("MainWindow", "Configuração"))
